# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: CC-BY-SA-4.0

title = "rollyourown.xyz template"

#Replace this URL with the URL for your domain
baseURL = "https://rollyourown.xyz"

theme = "ananke"
contentDir = "content"
defaultContentLanguage = "en"

SectionPagesMenu = "main"
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "rollyourown.xyz template"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  disable_share = true

##########################
# Privacy-related features
##########################
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
